version: "3.8"
services:
  app:
    build: .
    ports:
      - "9900:9900"
    environment:
      - MONGO_URI=mongodb://db:27017
      - PORT=9900
      - DB_NAME=short_link
      - COLLECTION_NAME=short_link_col
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
